name: Build & Release

on:
  push:
    tags:
      - '*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2 and install MinGW
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain
            
      - name: Configure CMake with MinGW
        run: cmake -B ${{ github.workspace }}/build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: ${{ github.workspace }}/build/bin/FingerPointer.exe

  create-release:
    name: Create GitHub Release with Artifacts
    needs: [build]
    runs-on: windows-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: exe
          path: artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: "artifacts/*.*"
